<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<div data-bind="scope: 'custom'">
    <button data-bind="click: toggleState">Toggle</button>
    <!-- ko if: isActive -->
        <div>is active</div>
    <!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom": {
                        "component": "Magento_Theme/js/view/custom"
                    }
                }
            }
        }
    }
</script>
