<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<div data-bind="scope: 'custom'">
    <!-- ko template: getTemplate() -->
        Loading...
    <!-- /ko -->
</div>



<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom": {
                        "component": "Magento_Theme/js/view/custom",
                        "text": "text from phtml"
                    }
                }
            }
        }
    }
</script>
