<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<div data-bind="scope: 'custom1'">
    <!-- ko template: getTemplate() -->
        Loading custom 1...
    <!-- /ko -->
</div>
<div data-bind="scope: 'custom2'">
    <!-- ko template: getTemplate() -->
    Loading custom 2...
    <!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom1": {
                        "component": "Magento_Theme/js/view/custom1"
                    },
                    "custom2": {
                        "component": "Magento_Theme/js/view/custom2"
                    }
                }
            }
        }
    }
</script>
