<div data-bind="scope: 'custom1'">
    <!-- ko template: getTemplate() -->Loading...<!--/ko-->
</div>
<div data-bind="scope: 'custom2'">
    <!-- ko template: getTemplate() -->Loading...<!--/ko-->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom1": {
                        "component": "Magento_Theme/js/view/uiDependencies/custom1",
                        "deps": ["custom2"]
                    },
                    "custom2": {
                        "component": "Magento_Theme/js/view/uiDependencies/custom2"
                    }
                }
            }
        }
    }
</script>
