<div data-bind="scope: 'custom'">
    <!-- ko template: getTemplate() -->Loading...<!--/ko-->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom": {
                        "component": "Magento_Theme/js/view/uiStatefull/custom"
                    }
                }
            }
        }
    }
</script>
