<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>
<div>
    <!-- parent.child (children) -->
    <div data-bind="scope: 'parent'">
        <!-- ko template: getTemplate() -->uiComponent-parent is loading...<!-- /ko -->
    </div>
    <?= $block->getChildHtml() ?>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "parent": {
                        "component": "Perspective_Module/js/view/uiComponent-parent"
                    }
                }
            }
        }
    }
</script>
